In [1]:
import pandas as pd

df = pd.read_csv('../dataset/email_spam_indo.csv')
df.head()

  Kategori                                              Pesan
0     spam  Secara alami tak tertahankan identitas perusah...
1     spam  Fanny Gunslinger Perdagangan Saham adalah Merr...
2     spam  Rumah -rumah baru yang luar biasa menjadi muda...
3     spam  4 Permintaan Khusus Pencetakan Warna Informasi...
4     spam  Jangan punya uang, dapatkan CD perangkat lunak...

In [2]:
df = df.rename(columns={
    'Pesan': 'text',
    'Kategori': 'label'
})

In [3]:
import re

def preprocess(text):
    text = text.lower()
    text = re.sub(r'http\S+', '', text)
    text = re.sub(r'(dikeret oleh|ditahan oleh|ect pada|subjek:).*', '', text, flags=re.IGNORECASE)
    text = re.sub(r'\b\w+\s+(com|net|org|co|id)\b', '', text)
    text = re.sub(r'\S+@\S+', '', text)
    text = re.sub(r'^(re|fw|fwd):[^.?!\n]*', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df['clean_text'] = df['text'].apply(preprocess)
df[['text', 'clean_text']].head()

,text,clean_text
0,Secara alami tak tertahankan identitas perusah...,secara alami tak tertahankan identitas perusah...
1,Fanny Gunslinger Perdagangan Saham adalah Merr...,fanny gunslinger perdagangan saham adalah merr...
2,Rumah -rumah baru yang luar biasa menjadi muda...,rumah rumah baru yang luar biasa menjadi mudah...
3,4 Permintaan Khusus Pencetakan Warna Informasi...,permintaan khusus pencetakan warna informasi t...
4,"Jangan punya uang, dapatkan CD perangkat lunak...",jangan punya uang dapatkan cd perangkat lunak ...

In [4]:
NORMALIZATION_DICT = {
    # 🔤 Singkatan umum
    "gk": "tidak",
    "d": "di",
    "ga": "tidak",
    "gak": "tidak",
    "nggak": "tidak",
    "tdk": "tidak",
    "dr": "dari",
    "dgn": "dengan",
    "utk": "untuk",
    "yg": "yang",
    "jg": "juga",
    "krn": "karena",
    "blm": "belum",
    "sdh": "sudah",
    "aja": "saja",
    "trs": "terus",
    "bgt": "banget",
    "dlm": "dalam",

    # 💰 Kata khas spam / promo
    "rp": "rupiah",
    "jt": "juta",
    "rb": "ribu",
    "cashback": "cashback",
    "promo": "promosi",
    "diskon": "diskon",
    "gratis": "gratis",
    "hadiah": "hadiah",
    "menang": "menang",
    "undian": "undian",

    # 📱 Variasi kata penting
    "tlp": "telepon",
    "telp": "telepon",
    "hp": "handphone",
    "no": "nomor",
    "rek": "rekening",
    "an": "atas nama",

    # ⚡ Variasi penulisan spam
    "selamat!!!": "selamat",
    "selamat!!": "selamat",
    "selamat!": "selamat",
    "trnsfer": "transfer",
    "trf": "transfer",

    # 🧩 Variasi angka ke huruf (leetspeak)
    "4nda": "anda",
    "4pa": "apa",
    "1ni": "ini",
    "k4mu": "kamu",

    # 🪤 Kata clickbait spam
    "klik": "klik",
    "segera": "segera",
    "buruan": "cepat",
    "cepat": "cepat",
    "terbatas": "terbatas",
    "khusus": "khusus",

    # 🎯 Kata inti spam
    "free": "gratis",
    "win": "menang",
    "winner": "pemenang",
    "prize": "hadiah",
    "bonus": "bonus",
    "gift": "hadiah",
    "reward": "hadiah",

    # 💰 Finansial / uang
    "cash": "uang",
    "money": "uang",
    "credit": "kredit",
    "loan": "pinjaman",
    "bank": "bank",
    "transfer": "transfer",
    "account": "akun",
    "sspecial": "spesial",
    "balance": "saldo",

    # 📢 Promosi / marketing
    "promo": "promosi",
    "offer": "penawaran",
    "deal": "penawaran",
    "discount": "diskon",
    "sale": "diskon",
    "limited": "terbatas",
    "exclusive": "eksklusif",

    # ⚡ Call to action (penting banget buat spam)
    "click": "klik",
    "claim": "klaim",
    "buy": "beli",
    "order": "pesan",
    "register": "daftar",
    "subscribe": "langganan",
    "join": "gabung",
    "verify": "verifikasi",
    "confirm": "konfirmasi",

    # ⏰ urgency
    "urgent": "segera",
    "now": "sekarang",
    "today": "hari ini",
    "instant": "instan",

    # 🖥️ teknologi / produk
    "software": "perangkat lunak",
    "system": "sistem",
    "update": "pembaruan",
    "download": "unduh",
    "install": "instal",

    # 📧 email umum
    "hello": "halo",
    "dear": "halo",
    "sir": "bapak",
    "madam": "ibu",

    # 🧩 lain-lain yang sering muncul
    "service": "layanan",
    "customer": "pelanggan",
    "support": "dukungan",
    "information": "informasi",
    "message": "pesan"
}
def normalize_text(text):
    words = text.split()
    normalized_words = [NORMALIZATION_DICT.get(word, word) for word in words]
    return ' '.join(normalized_words)

df['normalized_text'] = df['clean_text'].apply(normalize_text)
df[['text', 'clean_text','normalized_text']].head()

,text,clean_text,normalized_text
0,Secara alami tak tertahankan identitas perusah...,secara alami tak tertahankan identitas perusah...,secara alami tak tertahankan identitas perusah...
1,Fanny Gunslinger Perdagangan Saham adalah Merr...,fanny gunslinger perdagangan saham adalah merr...,fanny gunslinger perdagangan saham adalah merr...
2,Rumah -rumah baru yang luar biasa menjadi muda...,rumah rumah baru yang luar biasa menjadi mudah...,rumah rumah baru yang luar biasa menjadi mudah...
3,4 Permintaan Khusus Pencetakan Warna Informasi...,permintaan khusus pencetakan warna informasi t...,permintaan khusus pencetakan warna informasi t...
4,"Jangan punya uang, dapatkan CD perangkat lunak...",jangan punya uang dapatkan cd perangkat lunak ...,jangan punya uang dapatkan cd perangkat lunak ...

In [5]:
!pip install Sastrawi
!pip install nltk

Requirement already satisfied: Sastrawi in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (1.0.1)

WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: nltk in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (3.9.2)
Requirement already satisfied: click in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from nltk) (1.3.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from click->nltk) (0.4.6)

WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory

# ambil stopword default
factory = StopWordRemoverFactory()
stopwords = set(factory.get_stop_words())

# fungsi hapus stopword
def remove_stopwords(text):
    return ' '.join([word for word in text.split() if word not in stopwords])

# apply ke data
df['stopwords'] = df['normalized_text'].apply(remove_stopwords)

# lihat hasil
df[['text', 'normalized_text', 'stopwords']].head()

,text,normalized_text,stopwords
0,Secara alami tak tertahankan identitas perusah...,secara alami tak tertahankan identitas perusah...,alami tak tertahankan identitas perusahaan san...
1,Fanny Gunslinger Perdagangan Saham adalah Merr...,fanny gunslinger perdagangan saham adalah merr...,fanny gunslinger perdagangan saham merrill muz...
2,Rumah -rumah baru yang luar biasa menjadi muda...,rumah rumah baru yang luar biasa menjadi mudah...,rumah rumah baru luar biasa menjadi mudah menu...
3,4 Permintaan Khusus Pencetakan Warna Informasi...,permintaan khusus pencetakan warna informasi t...,permintaan khusus pencetakan warna informasi t...
4,"Jangan punya uang, dapatkan CD perangkat lunak...",jangan punya uang dapatkan cd perangkat lunak ...,jangan punya uang dapatkan cd perangkat lunak ...

In [7]:
# tokenization
df['tokens'] = df['stopwords'].apply(lambda x: x.split())

# lihat hasil
df[['text', 'clean_text', 'stopwords', 'tokens']].head()

,text,clean_text,stopwords,tokens
0,Secara alami tak tertahankan identitas perusah...,secara alami tak tertahankan identitas perusah...,alami tak tertahankan identitas perusahaan san...,"[alami, tak, tertahankan, identitas, perusahaa..."
1,Fanny Gunslinger Perdagangan Saham adalah Merr...,fanny gunslinger perdagangan saham adalah merr...,fanny gunslinger perdagangan saham merrill muz...,"[fanny, gunslinger, perdagangan, saham, merril..."
2,Rumah -rumah baru yang luar biasa menjadi muda...,rumah rumah baru yang luar biasa menjadi mudah...,rumah rumah baru luar biasa menjadi mudah menu...,"[rumah, rumah, baru, luar, biasa, menjadi, mud..."
3,4 Permintaan Khusus Pencetakan Warna Informasi...,permintaan khusus pencetakan warna informasi t...,permintaan khusus pencetakan warna informasi t...,"[permintaan, khusus, pencetakan, warna, inform..."
4,"Jangan punya uang, dapatkan CD perangkat lunak...",jangan punya uang dapatkan cd perangkat lunak ...,jangan punya uang dapatkan cd perangkat lunak ...,"[jangan, punya, uang, dapatkan, cd, perangkat,..."

In [8]:
!pip install pycaret scikit-learn gensim

Requirement already satisfied: pycaret in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (3.3.2)

WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~treamlit (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)
WARNING: Ignoring invalid distribution ~vicorn (C:\Users\barun\AppData\Local\Programs\Python\Python311\Lib\site-packages)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: scikit-learn in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (1.4.2)
Requirement already satisfied: gensim in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (4.4.0)
Requirement already satisfied: ipython>=5.5.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (8.14.0)
Requirement already satisfied: ipywidgets>=7.6.5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (8.1.0)
Requirement already satisfied: tqdm>=4.62.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (4.67.1)
Requirement already satisfied: numpy<1.27,>=1.21 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (1.26.4)
Requirement already satisfied: pandas<2.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (2.1.4)
Requirement already satisfied: jinja2>=3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (3.1.6)
Requirement already satisfied: scipy<=1.11.4,>=1.6.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (1.11.4)
Requirement already satisfied: joblib<1.4,>=1.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (1.3.2)
Requirement already satisfied: pyod>=1.1.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: imbalanced-learn>=0.12.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (0.14.1)
Requirement already satisfied: category-encoders>=2.4.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (2.7.0)
Requirement already satisfied: lightgbm>=3.0.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (4.6.0)
Requirement already satisfied: numba>=0.55.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (0.62.1)
Requirement already satisfied: requests>=2.27.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (2.32.5)
Requirement already satisfied: psutil>=5.9.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (5.9.5)
Requirement already satisfied: markupsafe>=2.0.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (2.1.3)
Requirement already satisfied: importlib-metadata>=4.12.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (6.8.0)
Requirement already satisfied: nbformat>=4.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (5.9.2)
Requirement already satisfied: cloudpickle in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (3.1.2)
Requirement already satisfied: deprecation>=2.1.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (2.1.0)
Requirement already satisfied: xxhash in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (3.5.0)
Requirement already satisfied: matplotlib<3.8.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (3.7.2)
Requirement already satisfied: scikit-plot>=0.3.7 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (0.3.7)
Requirement already satisfied: yellowbrick>=1.4 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (1.5)
Requirement already satisfied: plotly>=5.14.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (5.24.1)
Requirement already satisfied: kaleido>=0.2.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (1.2.0)
Requirement already satisfied: schemdraw==0.15 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (0.15)
Requirement already satisfied: plotly-resampler>=0.8.3.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (0.11.0)
Requirement already satisfied: statsmodels>=0.12.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (0.14.5)
Requirement already satisfied: sktime==0.26.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (0.26.0)
Requirement already satisfied: tbats>=1.1.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (1.1.3)
Requirement already satisfied: pmdarima>=2.0.4 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pycaret) (2.0.4)
Requirement already satisfied: packaging in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from sktime==0.26.0->pycaret) (23.2)
Requirement already satisfied: scikit-base<0.8.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from sktime==0.26.0->pycaret) (0.7.8)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<3.8.0->pycaret) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<3.8.0->pycaret) (4.57.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<3.8.0->pycaret) (1.4.8)
Requirement already satisfied: pillow>=6.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<3.8.0->pycaret) (10.1.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<3.8.0->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from matplotlib<3.8.0->pycaret) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pandas<2.2.0->pycaret) (2023.3)
Requirement already satisfied: smart_open>=1.8.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from gensim) (7.5.0)
Requirement already satisfied: patsy>=0.5.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from category-encoders>=2.4.0->pycaret) (1.0.1)
Requirement already satisfied: sklearn-compat<0.2,>=0.1.5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from imbalanced-learn>=0.12.0->pycaret) (0.1.5)
Requirement already satisfied: zipp>=0.5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from importlib-metadata>=4.12.0->pycaret) (3.16.2)
Requirement already satisfied: backcall in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: decorator in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (0.19.0)
Requirement already satisfied: matplotlib-inline in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pickleshare in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (3.0.39)
Requirement already satisfied: pygments>=2.4.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (2.15.1)
Requirement already satisfied: stack-data in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (0.6.2)
Requirement already satisfied: traitlets>=5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (5.9.0)
Requirement already satisfied: colorama in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipython>=5.5.0->pycaret) (0.4.6)
Requirement already satisfied: wcwidth in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30->ipython>=5.5.0->pycaret) (0.2.6)
Requirement already satisfied: comm>=0.1.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (0.1.4)
Requirement already satisfied: widgetsnbextension~=4.0.7 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.8)
Requirement already satisfied: jupyterlab-widgets~=3.0.7 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.8)
Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from jedi>=0.16->ipython>=5.5.0->pycaret) (0.8.3)
Requirement already satisfied: choreographer>=1.1.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from kaleido>=0.2.1->pycaret) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from kaleido>=0.2.1->pycaret) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from kaleido>=0.2.1->pycaret) (3.10.18)
Requirement already satisfied: pytest-timeout>=2.4.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from kaleido>=0.2.1->pycaret) (2.4.0)
Requirement already satisfied: simplejson>=3.19.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from choreographer>=1.1.1->kaleido>=0.2.1->pycaret) (3.20.2)
Requirement already satisfied: fastjsonschema in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from nbformat>=4.2.0->pycaret) (2.18.0)
Requirement already satisfied: jsonschema>=2.6 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from nbformat>=4.2.0->pycaret) (4.24.0)
Requirement already satisfied: jupyter-core in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from nbformat>=4.2.0->pycaret) (5.3.1)
Requirement already satisfied: attrs>=22.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (23.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.30.1)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from jsonschema>=2.6->nbformat>=4.2.0->pycaret) (0.9.2)
Requirement already satisfied: llvmlite<0.46,>=0.45.0dev0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from numba>=0.55.0->pycaret) (0.45.1)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from plotly>=5.14.0->pycaret) (8.2.3)
Requirement already satisfied: dash>=2.11.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (4.1.0)
Requirement already satisfied: tsdownsample>=0.1.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from plotly-resampler>=0.8.3.1->pycaret) (0.1.4.1)
Requirement already satisfied: Flask<3.2,>=1.0.4 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.2)
Requirement already satisfied: Werkzeug<3.2 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (3.1.3)
Requirement already satisfied: typing_extensions>=4.1.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (4.14.1)
Requirement already satisfied: retrying in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.4.2)
Requirement already satisfied: nest-asyncio in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.5.7)
Requirement already satisfied: setuptools in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (65.5.0)
Requirement already satisfied: blinker>=1.9.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (1.9.0)
Requirement already satisfied: click>=8.1.3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (8.3.1)
Requirement already satisfied: itsdangerous>=2.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from Flask<3.2,>=1.0.4->dash>=2.11.0->plotly-resampler>=0.8.3.1->pycaret) (2.2.0)
Requirement already satisfied: Cython!=0.29.18,!=0.29.31,>=0.29 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pmdarima>=2.0.4->pycaret) (3.2.4)
Requirement already satisfied: urllib3 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pmdarima>=2.0.4->pycaret) (2.5.0)
Requirement already satisfied: pytest>=7.0.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (9.0.3)
Requirement already satisfied: iniconfig>=1.0.1 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido>=0.2.1->pycaret) (1.6.0)
Requirement already satisfied: six>=1.5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from python-dateutil>=2.7->matplotlib<3.8.0->pycaret) (1.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.27.1->pycaret) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.27.1->pycaret) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from requests>=2.27.1->pycaret) (2026.2.25)
Requirement already satisfied: wrapt in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from smart_open>=1.8.1->gensim) (1.14.2)
Requirement already satisfied: platformdirs>=2.5 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (3.10.0)
Requirement already satisfied: pywin32>=300 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from jupyter-core->nbformat>=4.2.0->pycaret) (311)
Requirement already satisfied: executing>=1.2.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (1.2.0)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (2.2.1)
Requirement already satisfied: pure-eval in c:\users\barun\appdata\local\programs\python\python311\lib\site-packages (from stack-data->ipython>=5.5.0->pycaret) (0.2.2)

In [9]:
import pandas as pd
import numpy as np
from gensim.models import Word2Vec

# Model Word2Vec butuh data berformat list kata per kalimat (ada di df['tokens'])
# Kita buat 100 fitur/dimensi vektor untuk setiap kalimat
w2v_model = Word2Vec(sentences=df['tokens'], vector_size=100, window=5, min_count=2, workers=4)

# Fungsi pembuat Sentence/Document Vector (Rata-rata fitur vektor dari kumpulan kata)
def document_vector(doc):
    valid_words = [word for word in doc if word in w2v_model.wv.key_to_index]
    if len(valid_words) == 0:
        return np.zeros(100)
    return np.mean(w2v_model.wv[valid_words], axis=0)

X_w2v = np.array(df['tokens'].apply(document_vector).tolist())

# Susun ke bentuk DataFrame untuk PyCaret
feature_names = [f"w2v_{i}" for i in range(100)]
df_pycaret = pd.DataFrame(X_w2v, columns=feature_names)
df_pycaret['label'] = df['label'].values

df_pycaret.head()

,w2v_0,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,...,w2v_91,w2v_92,w2v_93,w2v_94,w2v_95,w2v_96,w2v_97,w2v_98,w2v_99,label
0,0.062616,0.852241,0.542056,-0.068858,-0.250792,-0.643764,0.115303,0.699246,-0.132693,-0.684864,...,0.081326,0.264982,0.459792,1.100665,0.099204,0.845415,-0.572950,0.329304,-0.273980,spam
1,-0.005855,0.375089,0.315938,-0.031259,-0.132917,-0.461248,0.133113,0.535756,-0.180179,-0.402832,...,-0.003439,0.192877,0.205998,0.602202,0.095859,0.323144,-0.431961,0.304939,-0.158806,spam
2,0.097316,0.692441,0.492338,-0.103231,-0.222280,-0.701223,0.126632,0.845231,-0.209037,-0.645053,...,0.040314,0.258201,0.528277,1.061614,0.129379,0.682857,-0.639576,0.348959,-0.306694,spam
3,0.108594,0.297771,0.164841,-0.310617,0.409755,-1.095954,-0.299441,1.622640,-0.065684,0.048288,...,0.259571,0.718269,0.583605,1.116216,0.433280,-0.049076,-0.331824,-0.057768,-0.137450,spam
4,0.142632,0.592080,0.279907,-0.004921,-0.226180,-0.302473,0.342426,0.961478,-0.628749,-0.205387,...,0.291008,0.337070,0.539857,1.218750,0.229793,0.376225,-0.209806,0.442308,-0.678148,spam

In [10]:
from pycaret.classification import ClassificationExperiment

# Inisialisasi Environment PyCaret berbasis Object Khusus untuk W2V
exp_w2v = ClassificationExperiment()
clf_setup = exp_w2v.setup(data=df_pycaret, target='label', session_id=42, use_gpu=False)

In [11]:
# Membandingkan model SVM, Naive Bayes (nb), dan Logistic Regression (lr)
best_model = exp_w2v.compare_models(include=['svm', 'nb', 'lr'])